            std::wstring loremIpsumArticleWiki = L"Lorem ipsum\n\n"
                                   L"An example of the Lorem ipsum placeholder text on a green and white webpage.\n"
                                   L"Using Lorem ipsum to focus attention on graphic elements in a webpage design proposal\n\n"
                                   L"One of the earliest examples of the Lorem ipsum placeholder text on 1960s advertising.\n"
                                   L"In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to "
                                   L"demonstrate the visual form of a document or a typeface without relying on meaningful "
                                   L"content. Lorem ipsum may be used as a placeholder before final copy is available. It "
                                   L"is also used to temporarily replace text in a process called greeking, which allows "
                                   L"designers to consider the form of a webpage or publication, without the meaning of the "
                                   L"text influencing the design.\n\n"
                                   L"Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century "
                                   L"BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed "
                                   L"to make it nonsensical and improper Latin. The first two words themselves are a truncation of "
                                   L"\'dolorem ipsum\' (\'pain itself\').\n\n"
                                   L"Versions of the Lorem ipsum text have been used in typesetting at least since the 1960s, when "
                                   L"it was popularized by advertisements for Letraset transfer sheets.[1] Lorem ipsum was introduced "
                                   L"to the digital world in the mid-1980s, when Aldus employed it in graphic and word-processing "
                                   L"templates for its desktop publishing program PageMaker. Other popular word processors, including "
                                   L"Pages and Microsoft Word, have since adopted Lorem ipsum,[2] as have many LaTeX packages,[3][4][5] "
                                   L"web content managers such as Joomla! and WordPress, and CSS libraries such as Semantic UI.[6]\n\n"
                                   L"Example text\n"
                                   L"A common form of Lorem ipsum reads:\n"
                                   L"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut "
                                   L"labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris "
                                   L"nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit "
                                   L"esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt "
                                   L"in culpa qui officia deserunt mollit anim id est laborum.\n\n"
                                   L"Source text\n\n"
                                   L"This article possibly contains original research. The citation only links the translation; The "
                                   L"highlighting appears to be user-generated. Please improve it by verifying the claims made and "
                                   L"adding inline citations. Statements consisting only of original research should be removed. "
                                   L"(October 2023) (Learn how and when to remove this template message)\n"
                                   L"The Lorem ipsum text is derived from sections 1.10.32 and 1.10.33 of Cicero\'s De finibus bonorum "
                                   L"et malorum.[7][8] The physical source may have been the 1914 Loeb Classical Library edition of De "
                                   L"finibus, where the Latin text, presented on the left-hand (even) pages, breaks off on page 34 with "
                                   L"\"Neque porro quisquam est qui do-\" and continues on page 36 with \"lorem ipsum ...\", suggesting "
                                   L"that the galley type of that page was mixed up to make the dummy text seen today.[1]\n"
                                   L"The discovery of the text's origin is attributed to Richard McClintock, a Latin scholar at "
                                   L"Hampden–Sydney College. McClintock connected Lorem ipsum to Cicero's writing sometime before 1982 "
                                   L"while searching for instances of the Latin word consectetur, which was rarely used in classical "
                                   L"literature.[2] McClintock first published his discovery in a 1994 letter to the editor of Before "
                                   L"& After magazine,[9] contesting the editor's earlier claim that Lorem ipsum held no meaning.[2]\n\n"
                                   L"The relevant section of Cicero as printed in the source is reproduced below with fragments used in "
                                   L"Lorem ipsum highlighted. Letters in brackets were added to Lorem ipsum and were not present in the "
                                   L"source text:\n\n"
                                   L"What follows is H. Rackham's translation, as printed in the 1914 Loeb edition, with words at least "
                                   L"partially represented in Lorem ipsum highlighted:[8]\n\n"
                                   L"[32] But I must explain to you how all this mistaken idea of reprobating pleasure and extolling "
                                   L"pain arose. To do so, I will give you a complete account of the system, and expound the actual "
                                   L"teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, "
                                   L"dislikes or avoids pleasure itself, because it is pleasure, but because those who do not know how "
                                   L"to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there "
                                   L"anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally "
                                   L"circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial "
                                   L"example, which of us ever undertakes laborious physical exercise, except to obtain some advantage "
                                   L"from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no "
                                   L"annoying consequences, or one who avoids a pain that produces no resultant pleasure?\n\n"
                                   L"[33] On the other hand, we denounce with righteous indignation and dislike men who are so beguiled "
                                   L"and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot "
                                   L"foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in "
                                   L"their duty through weakness of will, which is the same as saying through shrinking from toil and "
                                   L"pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of "
                                   L"choice is untrammeled and when nothing prevents our being able to do what we like best, every pleasure "
                                   L"is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty "
                                   L"or the obligations of business it will frequently occur that pleasures have to be repudiated and "
                                   L"annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: "
                                   L"he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.\n";

            std::wstring hogwartsWiki1 = L"Hogwarts\n\n"
                                   L"From Wikipedia, the free encyclopedia\n\n"
                                   L"Hogwarts School of Witchcraft and Wizardry is a fictional boarding school of magic for students aged eleven "
                                   L"to eighteen, and is the primary setting for the first six books in J. K. Rowling's Harry Potter series and "
                                   L"serves as a major setting in the Wizarding World universe.[3]\n\n"
                                   L"History\n\n"
                                   L"Establishment\n"
                                   L"Founded around the 9th century and 10th century by Godric Gryffindor, Rowena Ravenclaw, Helga Hufflepuff and "
                                   L"Salazar Slytherin, Hogwarts was established in the Highlands of Scotland to educate young wizards and witches "
                                   L"as well as to keep students safe from Muggle persecution. Theory has it that Rowena Ravenclaw came up with the "
                                   L"name of Hogwarts after dreaming of a warty hog that led her to a cliff by a lake.[4] Since then, Hogwarts "
                                   L"educated most wizarding children with residence in Great Britain and Ireland, keeping its location hidden "
                                   L"from other wizarding schools and Muggles.\n"
                                   L"Middle Ages\n"
                                   L"About 300 years after the school was founded, the Triwizard Tournament was established as an interscholastic "
                                   L"competition among the three most prestigious magical schools in Europe: Hogwarts, Beauxbatons, and Durmstrang. "
                                   L"The tournament continued for six centuries before being discontinued. An attempt was made in the 1994–1995 "
                                   L"school year to revive the tournament, but the consequential death of Cedric Diggory resulted in its permanent "
                                   L"discontinuation.[5]\n"
                                   L"Academics and traditions\n"
                                   L"Hogwarts is a coeducational, secondary boarding school, taking children from ages eleven to eighteen,[6] in "
                                   L"line with real-world combined secondary and sixth form institutions in Britain. Education at Hogwarts is not "
                                   L"compulsory, with some students being home schooled as stated in the seventh book. Rowling initially said there "
                                   L"are about one thousand students at Hogwarts.[7] She later suggested around six hundred, while acknowledging "
                                   L"that this number was still inconsistent with the small number of people in Harry's year. She further explained "
                                   L"that this had resulted from her creating only forty characters for Harry's year.[8]\n"
                                   L"Admission\n"
                                   L"According to the novels, admission to Hogwarts is selective, in that children who show magical ability will "
                                   L"automatically gain a place,[9] and squibs cannot attend the school as students (though they can work there in "
                                   L"other roles, as Argus Filch does).[10] A magical quill at Hogwarts detects the birth of magical children and "
                                   L"writes their names into a large parchment book,[1] but there is no admission test because \"you are either "
                                   L"magical or you are not\".[9] Every year, a teacher checks this book and sends a letter to the children who are "
                                   L"turning eleven. Acceptance or refusal of a place at Hogwarts must be posted by 31 July. The letter also contains "
                                   L"a list of supplies like spell books, uniform, and other things that the student will need. The prospective student "
                                   L"is expected to buy all the necessary materials, normally from shops in Diagon Alley, a concealed street near "
                                   L"Charing Cross Road in London that can be found behind the wizarding pub, The Leaky Cauldron. Students who cannot "
                                   L"afford their supplies can receive financial aid from the school, as happened with the young orphan Tom Riddle.\n"
                                   L"Letters to Muggle-born witches and wizards, who may not be aware of their powers and are unfamiliar with the "
                                   L"concealed wizarding world, are delivered in person by a member of Hogwarts staff, who then explains to the "
                                   L"parents or guardians about magical society, and reassures them regarding this news.[HP7]\n"
                                   L"Though the school is in Great Britain, its catchment area is the wider British Isles, as Irish students can "
                                   L"also attend.\n"
                                   L"Each student is allowed to bring an owl, a cat or a toad. Along with the acceptance letter, first-year students "
                                   L"are sent a list of required equipment which includes a wand, subject books, a standard size 2 pewter cauldron, "
                                   L"a set of brass scales, a set of glass or crystal phials, a kit of basic potion ingredients (for Potions), and a "
                                   L"telescope (for Astronomy). The Hogwarts uniform consists of plain work robes in black, a plain black hat, a pair "
                                   L"of protective gloves, and a black winter cloak with silver fastenings. Each uniform must contain the wearer's "
                                   L"nametag. First years are not allowed a broomstick of their own, though an exception to this rule is made for "
                                   L"Harry Potter in his first year after he demonstrates an excellent ability as a Seeker in Quidditch.\n"
                                   L"Arrival\n"
                                   L"The primary mode of transport to Hogwarts is the Hogwarts Express that students take at the start of each school "
                                   L"year. Students board the train from the also fictional and hidden Platform 9+3/4 at King's Cross station in London. "
                                   L"The train arrives at Hogsmeade station near Hogwarts, sometime after nightfall.\n"
                                   L"From there, first-year students are accompanied by the \"Keeper of the Keys, Game and Grounds\" (which was "
                                   L"Rubeus Hagrid during the first novel) to small boats, which magically sail across the lake and get them near "
                                   L"the entrance of Hogwarts. The older students ride up to the castle in carriages pulled by creatures called Thestrals. "
                                   L"When the first-year students initially arrive at the castle, they wait in a small chamber off the entrance hall "
                                   L"until the older students have taken their seats, and then enter the Great Hall for the Sorting Ceremony to determine "
                                   L"their House assignments. As Professor Minerva McGonagall said in Harry Potter and the Philosopher's Stone, \"The "
                                   L"Sorting is a very important ceremony because, while you are here, your House will be something like your family "
                                   L"within Hogwarts. You will have classes with the rest of your House, sleep in your House dormitory, and spend free "
                                   L"time in your House common room.\"\n"
                                   L"After the Sorting Hat sings a song, each student in turn is seated upon the stool in front of the rest of the "
                                   L"student body. The Hat is placed on the student's head, whereupon it examines his or her mind and assigns them to "
                                   L"one of the four Houses based on abilities, personality, and preferences. After the Sorting Ceremony, the students "
                                   L"and teachers enjoy a feast, prepared by the Hogwarts house-elves. If Albus Dumbledore is feeling cheerful, he will "
                                   L"lead the students in singing the school song.[11]\n"
                                   L"Houses\n"
                                   L"Hogwarts is divided into four houses, each bearing the last name of its founder: Godric Gryffindor, Salazar Slytherin, "
                                   L"Rowena Ravenclaw and Helga Hufflepuff. Throughout the school year, the houses compete for the House Cup, gaining and "
                                   L"losing points based on actions such as performance in class and rule violations. The house with the highest end-of-year "
                                   L"total wins and has its colours displayed in the Great Hall for the following school year. Each house also has its own "
                                   L"Quidditch team that competes for the Quidditch Cup. These two competitions breed rivalries between the houses. Houses "
                                   L"at Hogwarts are living and learning communities for their students. Each house is under the authority of one of the "
                                   L"Hogwarts staff members. The Heads of the houses, as they are called, are in charge of giving their students important "
                                   L"information, dealing with matters of severe punishment, and responding to emergencies in their houses, among other things. "
                                   L"The dormitory and common room of a House are, barring rare exceptions, inaccessible to students belonging to other Houses; "
                                   L"however, different houses will share classes as they are based on year group rather than House.\n"
                                   L"In the early days of Hogwarts, the four founders hand-picked students for their Houses. When the founders worried how "
                                   L"students would be selected after their deaths, Godric Gryffindor took his hat off and they each added knowledge to it, "
                                   L"allowing the Sorting Hat to choose the students by judging each student's qualities and placing them in the most "
                                   L"appropriate house. The student's own choices may affect the decision: the clearest example is the Hat telling Harry "
                                   L"that he would do well in Slytherin in the first book, but ultimately selecting Gryffindor after Harry asks it not "
                                   L"to put him in Slytherin.\n"
                                   L"The translators of the books' foreign editions had difficulty translating the \"house\" concept; in countries where "
                                   L"this system does not exist, no word could adequately convey the importance of belonging to a house, the loyalty "
                                   L"owed to it, and the pride taken in prizes won by the house.[12]\n";

            std::wstring hogwartsWiki2 = L"Gryffindor\n"
                                   L"Gryffindor values courage, bravery, nerve, and chivalry. Gryffindor's mascot is "
                                   L"the lion, and its colours are scarlet red and gold (maroon and gold on the ties "
                                   L"and scarves). During the books, the Head of this house is the Transfiguration "
                                   L"Professor and Deputy Headmistress, Minerva McGonagall until she becomes headmistress, "
                                   L"and the house ghost is Sir Nicholas de Mimsy-Porpington, more commonly known as "
                                   L"Nearly Headless Nick. According to Rowling, Gryffindor corresponds roughly to the "
                                   L"element of fire.[13] The founder of the house is Godric Gryffindor.\n"
                                   L"The Gryffindor common room is in one of the castle's highest towers, and its "
                                   L"entrance is on the seventh floor in the east wing of the castle and is guarded "
                                   L"by a painting of The Fat Lady, who is garbed in a pink dress. She permits entry "
                                   L"only after being given the correct password, as was established in the third book, "
                                   L"when Sirius Black tried forcing entry into the tower, only to be blocked by The "
                                   L"Fat Lady after he could not give the correct password. In the first book, Neville "
                                   L"Longbottom tends to forget the password and must wait near the painting until other "
                                   L"Gryffindors arrive to open the way.[14]\n"
                                   L"Hufflepuff\n"
                                   L"Hufflepuff values hard work, patience, justice, and loyalty. The house mascot is "
                                   L"the badger, and canary yellow and black (or golden yellow and graphite in the "
                                   L"Fantastic Beasts films) are its colours. During the books, the Head of this house "
                                   L"is the Herbology Professor Pomona Sprout, and the house ghost is the Fat Friar. "
                                   L"According to Rowling, Hufflepuff corresponds roughly to the element of earth.[13] "
                                   L"The founder of this house is Helga Hufflepuff.\n"
                                   L"The entrance to the Hufflepuff dormitories and common room entrance is concealed "
                                   L"in a pile of large barrels in an alcove in the corridor that holds the kitchen. "
                                   L"To enter, one must tap the barrel two from the bottom in the middle of the second "
                                   L"row in the rhythm of \"Helga Hufflepuff\". Unlike any other house, the Hufflepuff "
                                   L"common room has a repelling device that douses the illegal entrant in vinegar if "
                                   L"the wrong lid is tapped or the rhythm is wrong.[15] The Hufflepuff common room is "
                                   L"filled with yellow hangings and fat armchairs and it has little tunnels leading "
                                   L"to the dormitories, all of which have perfectly round doors, like barrel tops.[16]\n"
                                   L"Ravenclaw\n"
                                   L"Ravenclaw values intelligence, learning, wisdom and wit.[HP5][HP7] The house mascot "
                                   L"is an eagle (raven in the Harry Potter and Fantastic Beasts films) and the house "
                                   L"colours are blue and bronze (blue and silver in the Harry Potter and Fantastic "
                                   L"Beasts films). During the books, the head of this house is the Charms teacher, "
                                   L"Professor Filius Flitwick, and the house ghost is the Grey Lady. According to "
                                   L"Rowling, Ravenclaw corresponds roughly to the element of air.[13] The founder of "
                                   L"this house is Rowena Ravenclaw.\n"
                                   L"The dormitories are in Ravenclaw Tower, on the west side of Hogwarts. The common "
                                   L"room is round and filled with blue hangings and armchairs, has a domed ceiling "
                                   L"painted with stars and features a replica statue of Rowena wearing her diadem. "
                                   L"Harry also notes that Ravenclaws \"have a spectacular view of the surrounding mountains\". "
                                   L"A logical riddle must be solved to gain entry, whereas the Gryffindor and Slytherin "
                                   L"common rooms only require a password. Professor McGonagall, the head of the Gryffindor "
                                   L"House, solves the riddle accurately.\n"
                                   L"Slytherin\n"
                                   L"Slytherin values ambition, cunning, leadership, and resourcefulness; the Sorting Hat "
                                   L"said in Harry Potter and the Philosopher's Stone that Slytherins will do anything to "
                                   L"get their way. The house mascot of Slytherin is the serpent, and the house colours "
                                   L"are green and silver. Throughout the series, until the seventh book, the Head of House "
                                   L"is Professor Severus Snape. Then, the previous Head of House Professor Horace Slughorn "
                                   L"comes out of retirement, re-assuming authority after Snape becomes headmaster. The "
                                   L"ghost of Slytherin house is the Bloody Baron.[17] According to Rowling, Slytherin "
                                   L"corresponds roughly to the element of water.[13] The founder of this house is Salazar "
                                   L"Slytherin.\n"
                                   L"The Slytherin dormitories and common room are reached by speaking a password to a "
                                   L"patch of bare stone wall in the dungeons, which causes a hidden door to open. The "
                                   L"Slytherin common room is a long, low, dungeon-style room, under the Hogwarts Lake, "
                                   L"furnished with green lamps and carved armchairs. The room is described in the second "
                                   L"book as having a greenish glow.\n"
                                   L"The Sorting Hat claims that blood purity is a factor in selecting Slytherins, although "
                                   L"this is not mentioned until the fifth book. There is no reason to believe, however, "
                                   L"that Muggle-born students are not sorted there, merely that pure-blooded students are "
                                   L"more desirable to that house, as there are several examples of half-bloods in the "
                                   L"house – such as Snape and Tom Riddle/Voldemort – and Harry himself was only excluded "
                                   L"from the house at his own insistence. In Deathly Hallows, a group of Snatchers claim "
                                   L"that \"not many Mudbloods\" are sorted into Slytherin.\n"
                                   L"When believing Harry to be dead and thinking that he has victory in his grasp, Voldemort "
                                   L"proclaims his intention to abolish the other three houses and force all Hogwarts students "
                                   L"into Slytherin. This design is foiled by his defeat and death, after which Slytherin "
                                   L"becomes more diluted in its blood purity, no longer remaining the pure-blood bastion "
                                   L"it once was.\n"
                                   L"Subjects and teachers\n"
                                   L"Main articles: Subjects at Hogwarts and Hogwarts staff\n"
                                   L"Being a school of magic, many subjects at Hogwarts differ from the studies of a typical "
                                   L"school. Some subjects, such as History of Magic, derive from non-wizard – or muggle – "
                                   L"subjects, but many others, such as charms and apparition classes, are unique to the "
                                   L"wizarding world. There are twelve named teachers (referred to as Professors), each "
                                   L"specialising in a single subject. All professors are overseen by a school head and "
                                   L"deputy head. Transfiguration, Defence Against the Dark Arts, Charms, Potions, Astronomy, "
                                   L"History of Magic, and Herbology are compulsory subjects for the first five years, as "
                                   L"well as flying lessons. At the end of their second year, students are required to add "
                                   L"at least two optional subjects to their syllabus for the start of the third year. The "
                                   L"five choices are Arithmancy, Muggle Studies, Divination, Study of Ancient Runes and "
                                   L"Care of Magical Creatures. According to J.K. Rowling, \"very specialised subjects such "
                                   L"as alchemy are sometimes offered in the final two years, if there is sufficient demand.\"[18]\n"
                                   L"At the end of their fifth year, students take the Ordinary Wizarding Level (O.W.L.) "
                                   L"examinations for all subjects in which they are enrolled.[citation needed] Each "
                                   L"examination consists of a written knowledge test and, where applicable, a practical "
                                   L"demonstration of skills before a panel of proctors from the Ministry of Magic. Students "
                                   L"who achieve a high enough O.W.L. grade in a particular subject may take its advanced "
                                   L"course for the final two years, in preparation for the Nastily Exhausting Wizarding "
                                   L"Tests (N.E.W.T.) given at the end of the seventh year.\n"
                                   L"Daily life\n"
                                   L"Film set of The Great Hall, Hogwarts at Warner Bros. Studios, Leavesden, UK\n"
                                   L"The day begins at Hogwarts with breakfast in the Great Hall. Students sit at their "
                                   L"own House table and can eat and socialise, or finish homework. The Headmaster or "
                                   L"Headmistress eats with the professors at the High Table placed at the far end of the "
                                   L"hall. During breakfast, owls bring in the students' post, generally consisting of "
                                   L"The Daily Prophet, letters from parents or friends, or packages from home. A bell "
                                   L"signals the start of the first class of the morning at 9 am.\n"
                                   L"There are two long morning classes with a short break in between them for students "
                                   L"to get to their next class. After lunch, classes resume at 1 pm, and there is a break "
                                   L"around afternoon teatime before another class period. The classes are about one hour "
                                   L"in length, with occasional double periods lasting two hours. Classes end around five "
                                   L"o\'clock. First-year students get Friday afternoons off, while sixth- and seventh-year "
                                   L"students have several free periods during the week. In the evening, students eat their "
                                   L"dinner in the Great Hall, after which they are expected to be in their common rooms. "
                                   L"Astronomy classes take place late at night in the Astronomy Tower.\n"
                                   L"The Great Hall film set at Leavesden studios\n"
                                   L"The four House dormitories have secret entrances, generally known only to members of "
                                   L"that house and require a password (Gryffindor and Slytherin), riddle answer (Ravenclaw) "
                                   L"or ritual (Hufflepuff) in order to gain entrance. Inside is the common room, which "
                                   L"contains armchairs and sofas for the pupils and tables for studying and homework. "
                                   L"There are fireplaces to keep the rooms warm, and students either relax here in the "
                                   L"evenings or else complete their homework, but may complete their work in the bedroom. "
                                   L"There are notice boards in each common room and at other strategic points throughout "
                                   L"the school. The students sleep in their House dormitories, which branch off from the "
                                   L"common rooms. Each dormitory gets at least two rooms; one for boys and one for girls "
                                   L"(an enchantment prevents boys from entering the girls' area, although there is no spell "
                                   L"to prevent the reverse from occurring). Each student sleeps in a large four-poster bed "
                                   L"with bed covers and heavy curtains in the House colours, and thick white pillows. There "
                                   L"is a bedside table for each bed, and each dormitory has a jug of water and goblets on a "
                                   L"tray.\n"
                                   L"On designated weekends, Hogwarts students in their third year or higher, with a signed "
                                   L"permission slip, are permitted to walk to the nearby wizarding village of Hogsmeade, "
                                   L"where they can relax and enjoy the pubs, restaurants and shops. There appears to be a "
                                   L"good relationship between the school and the village, and the students get on well with "
                                   L"the locals. Favourite places in Hogsmeade include Honeydukes Sweetshop, Zonko's Joke Shop, "
                                   L"clothing stores such as Gladrags Wizardwear, the Shrieking Shack (regarded as the most "
                                   L"haunted building in Britain), the pubs The Three Broomsticks and The Hog's Head, and "
                                   L"Madam Puddifoot's coffee shop.\n"
                                   L"Food\n"
                                   L"The house-elves at Hogwarts amongst other duties provide all food to students and staff. "
                                   L"They cook a wide variety of dishes especially at the feasts. The various dishes are "
                                   L"prepared in the kitchens directly below the Great Hall. Within the kitchen are four "
                                   L"long tables directly aligned with the house tables in the great hall above. At meal "
                                   L"times the food is magically transported up, appearing directly in front of the students.[19]\n"
                                   L"Discipline\n"
                                   L"Apart from losing points from a house, serious misdeeds at Hogwarts are punishable by "
                                   L"detention. Whenever a student loses a house point, their house jewels (ruby for Gryffindors, "
                                   L"emeralds for Slytherin, sapphires for Ravenclaw, and diamonds for Hufflepuff) are taken away "
                                   L"from a glass hourglass located in every classroom. The same goes for adding points to the "
                                   L"specific house, although the teacher or prefect must conjure the gems from thin air.\n"
                                   L"According to the school caretaker, Argus Filch, detention meant subjection to various "
                                   L"forms of corporal punishment until recently. Arthur Weasley claimed still to bear physical "
                                   L"scars inflicted by Apollyon Pringle, Filch's predecessor. In present times, however, "
                                   L"detention usually involves assisting staff or faculty with tedious tasks. Examples of "
                                   L"detention include the one imposed on Harry by Dolores Umbridge in Order of the Phoenix. "
                                   L"In this case, Harry was forced to write, \"I must not tell lies\" repeatedly using a "
                                   L"magical quill which then carves what is written into the back of the writer's hand. "
                                   L"However, most teachers at the school never use this cruel punishment. In another case, "
                                   L"when Snape caught Harry using the Sectumsempra curse on Draco Malfoy, he was forced to "
                                   L"go through over a thousand boxes of files describing wrongdoers at Hogwarts and their "
                                   L"punishments. Harry was supposed to order them in alphabetical order, and rewrite the "
                                   L"cards whose words were hard to see or otherwise damaged. The Weasley twins Fred and "
                                   L"George Weasley had a whole drawer of these cards.\n"
                                   L"For even more serious offences, students may be suspended or even expelled from "
                                   L"Hogwarts. Harry and Ron Weasley are threatened with expulsion after crashing Ron's "
                                   L"car into the Whomping Willow at the start of their second year, and Harry is expelled "
                                   L"before the start of his fifth year (although the sentence is quickly changed to a "
                                   L"disciplinary hearing) after he is detected using magic in the presence of Muggles, a "
                                   L"serious offence among the wizarding community. Dumbledore argued in Harry's defence, "
                                   L"stating that it was done in self-defence, and that the Ministry has no authority to "
                                   L"expel students – such powers are invested in the Headmaster and the Board of Governors. "
                                   L"Snape has attempted to have Harry expelled, and he attempted to have Harry's father, "
                                   L"James Potter, expelled when they were at Hogwarts together. The only student known to "
                                   L"have been expelled is Hagrid, for the murder of Myrtle with an acromantula believed to "
                                   L"be the Monster of Slytherin and for opening the Chamber of Secrets – crimes for which "
                                   L"Tom Riddle had framed him.\n"
                                   L"Professors seem to be able to punish students with relative impunity and can hand out "
                                   L"detention, even for unsatisfactory grades. Enforcement of rules outside of class mainly "
                                   L"falls to the caretaker, with the assistance of the prefects. A student's Head of House "
                                   L"usually has the final say in disciplinary matters. However, during Umbridge's tenure "
                                   L"at Hogwarts, she quickly obtains the power to have the final say in disciplinary "
                                   L"actions, due to an Educational Decree (one of many) passed by Minister for Magic "
                                   L"Cornelius Fudge.\n"
                                   L"In the summer before their fifth year, two fifth year students from each House are "
                                   L"picked to be prefects, which grants them privileges and responsibilities and "
                                   L"disciplinary responsibilities. The leaders of the student body, the Head Boy and "
                                   L"Head Girl, are drawn from the seventh year students. Prefects have the authority "
                                   L"to give detentions for infractions.\n";

            std::wstring hogwartsWiki3 = L"Castle and grounds\n"
                                   L"A huge, rambling, quite scary-looking castle, with a jumble of towers and battlements. "
                                   L"Like the Weasleys' house, it isn't a building that Muggles could build, because it is "
                                   L"supported by magic.[1]\n"
                                   L"In the novels, Hogwarts is somewhere in Scotland[20] (the film Prisoner of Azkaban says "
                                   L"that Dufftown is near). The school is depicted as having numerous charms and spells on "
                                   L"and around it that make it impossible for a Muggle to locate it. Muggles cannot see the "
                                   L"school; rather, they see only ruins and several warnings of danger.[GF Ch.11] The castle's "
                                   L"setting is described as having extensive grounds with sloping lawns, flowerbeds and vegetable "
                                   L"patches, a loch (called The Black Lake), a large dense forest (called the Forbidden Forest), "
                                   L"several greenhouses and other outbuildings, and a full-size Quidditch pitch. There is also an "
                                   L"owlery, which houses all the owls owned by the school and those owned by students. Some rooms "
                                   L"in the school tend to \"move around\", and so do the stairs in the grand staircase.[21] Witches "
                                   L"and wizards cannot Apparate or Disapparate in Hogwarts grounds, except when the Headmaster "
                                   L"lifts the enchantment, whether only in certain areas or for the entire campus, so as to make "
                                   L"the school less vulnerable when it serves the headmaster to allow Apparition.[GF Ch.28] "
                                   L"Electricity and electronic devices are not found at Hogwarts. Hermione Granger indicates in "
                                   L"Harry Potter and the Goblet of Fire that due to the high levels of magic, \"substitutes for "
                                   L"magic (that) Muggles use\" such as computers, radar and electricity \"go haywire\" around "
                                   L"Hogwarts. Radios however, make an exception. Rowling explains this by saying that the radios "
                                   L"are not powered by electricity but by magic.\n"
                                   L"Hogwarts is on the shore of a lake, sometimes called the Black Lake. In that lake are merpeople, "
                                   L"Grindylows, and a giant squid. The giant squid does not attack humans and sometimes acts as a "
                                   L"lifeguard when students are in the lake. The castle and its grounds are home to many secret "
                                   L"areas as well as well-known and well-used places.\n"
                                   L"Hiding place of the Philosopher's Stone\n"
                                   L"Accessed by entering a trapdoor in the forbidden corridor on the third floor, and protected "
                                   L"by a gauntlet of seven magical challenges set up by the teachers.\n"
                                   L"A giant three-headed dog named Fluffy placed specially to guard the trapdoor by Hagrid.\n"
                                   L"Devil's Snare, grown by Professor Sprout.\n"
                                   L"A room containing dozens of keys, charmed by Flitwick to sprout wings and fly near the "
                                   L"ceiling. One of these keys will unlock the door to the next section. However, in the "
                                   L"film adaptation, the keys attack the seeker of the Stone.\n"
                                   L"A large chessboard with an army of large chessmen, transfigured by McGonagall. To "
                                   L"continue to the door on the opposite side, the person in question must beat the chessmen "
                                   L"at a game of wizards' chess where the player must risk his life if he loses. Ron and "
                                   L"Professor Quirrell are the only wizards to win the game of wizards' chess.\n"
                                   L"A room with a large troll inside. This is Quirrell's challenge. In the book, Quirrell "
                                   L"had knocked out his own troll to get to the last room and thus the trio did not have "
                                   L"to fight it; in the film, it does not appear, but it appears in the PS1 and Game Boy "
                                   L"Color version of the game.\n"
                                   L"A series of potions, brewed by Snape. A logical riddle, not magic, has to be solved. "
                                   L"There are two doors, blocked by fire. One potion will allow the person to exit the "
                                   L"way he or she arrived, another will allow him or her to continue to the next chamber, "
                                   L"two are nettle wine, and the other three are poison. This challenge does not appear "
                                   L"in the film, but does in the video game adaptation.\n"
                                   L"The Mirror of Erised can be found in the final chamber, further enchanted by Dumbledore "
                                   L"to bestow the Philosopher's Stone upon a seeker only hoping to acquire the stone but "
                                   L"not use it for selfish means.\n"
                                   L"Chamber of Secrets\n"
                                   L"\"Chamber of Secrets\" redirects here. For other uses, see Chamber of Secrets (disambiguation).\n"
                                   L"The Chamber of Secrets, which is deep under the school (most likely under the lake),[22] "
                                   L"was home to an ancient Basilisk, intended to be used to purge the school of Muggle-born "
                                   L"students. Salazar Slytherin, one of the founders of Hogwarts, built the Chamber before "
                                   L"he left the school.\n"
                                   L"The entrance to the Chamber is hidden in the second-floor girls' lavatory (haunted by "
                                   L"Moaning Myrtle). One of the sink taps has a snake scratched into its side; when a "
                                   L"command in Parseltongue is spoken, it opens to reveal the mouth of a dark, slimy chute, "
                                   L"wide enough to slide down, that gives onto a stone tunnel. There are many skeletons of "
                                   L"small animals littering the floor and even a gigantic skin shed by the Basilisk. The "
                                   L"tunnel leads to a solid wall, carved with two entwined serpents with emeralds for "
                                   L"eyes.[22] At a command in Parseltongue, the wall opens to expose a long, dim corridor, "
                                   L"lined with monumental statues of snakes, including two rows of towering stone pillars "
                                   L"with more carved serpents that brace the ceiling. A colossal statue of Salazar Slytherin, "
                                   L"looking ancient and monkey-like, is at the centre. The Basilisk rested inside the statue "
                                   L"and emerged from its mouth when the Heir of Slytherin, Tom Riddle, summoned it.[23] In "
                                   L"his second year at Hogwarts, Harry uses Parseltongue to open the chamber and destroys "
                                   L"the diary containing the embodied memory of a 16-year-old Tom Riddle from his own days "
                                   L"at Hogwarts and also slays the basilisk. It is later revealed that the diary was a Horcrux. "
                                   L"In Deathly Hallows, Ron and Hermione enter the Chamber. Ron opens the door (despite not "
                                   L"speaking Parseltongue) by imitating sounds he heard Harry use to open Slytherin's locket. "
                                   L"They pull a basilisk fang from its skeleton to use to destroy the Horcrux made from "
                                   L"Helga Hufflepuff's cup.\n"
                                   L"When Tom Riddle opened the Chamber, Myrtle was sulking in a stall after being teased "
                                   L"by student Olive Hornby. She opened the door, intending to tell him to leave, but died "
                                   L"immediately upon meeting the Basilisk's gaze and decided to become a ghost to get "
                                   L"revenge on Hornby.[22] The bathroom remains operational, but is rarely used by students "
                                   L"because of Myrtle's disagreeable presence and her habit of flooding it when she is "
                                   L"distraught.\n"
                                   L"The film's depiction of the Chamber has snake heads in place of the pillars and Slytherin's "
                                   L"statue is only his head. Rowling reveals in the book Harry Potter Page to Screen; The "
                                   L"Complete Filmmaking Journey that the Chamber has flooded since its creation under "
                                   L"unknown circumstances.\n"
                                   L"As shown in Deathly Hallows, the Chamber of Secrets does not appear on the Marauder's Map.\n"
                                   L"Passages\n"
                                   L"There are usually seven secret passages in and out of the school, and in addition, the "
                                   L"series describes the use of twin vanishing cabinets to create another. Filch knows of "
                                   L"just four of these, while the Marauders (James Potter, Sirius Black, Remus Lupin and "
                                   L"Peter Pettigrew) and the Weasley twins know of all seven, though where some lead is "
                                   L"unknown. The Room of Requirement may, on occasion, create an eighth passage out of the "
                                   L"school. The only known instance of this occurring is a passage to the Hog's Head that "
                                   L"forms in Deathly Hallows. Due to the nature of the Room of Requirement, it is possible "
                                   L"that several passages to different locations could be accessed from the Room. The three "
                                   L"passages out of Hogwarts that Filch does not know about are:\n"
                                   L"A passage beneath the Whomping Willow, leading to the Shrieking Shack.\n"
                                   L"A passage behind a mirror on the fourth floor, which is caved in. It leads to Hogsmeade, "
                                   L"but it is not known exactly where.\n"
                                   L"A passage beneath the one-eyed witch statue by the stairs to the Defence Against the "
                                   L"Dark Arts classroom, leading to the cellar of Honeydukes. Speaking aloud the word "
                                   L"'Dissendium' to the witch allows access to this passage; the hump on the statue then "
                                   L"opens and reveals the hidden passageway.\n"
                                   L"A further link between two vanishing cabinets, one in the school and the other in Borgin "
                                   L"and Burkes in Knockturn Alley presumably works until Chamber of Secrets when Peeves "
                                   L"(persuaded by Nearly Headless Nick) smashes the Hogwarts cabinet. The passage is "
                                   L"reopened in Half-Blood Prince when Draco Malfoy fixes the cabinet. This passage is "
                                   L"not shown on the Marauder's Map as it is not part of the castle itself.\n"
                                   L"Besides passages in and out of the school, there are also numerous short-cuts that "
                                   L"lead from one part of the castle to another. These are often concealed in such "
                                   L"fashions as a tapestry which hides a hole in the wall.\n"
                                   L"Room of Requirement\n"
                                   L"On the seventh floor opposite an enormous tapestry depicting Barnabas the Barmy "
                                   L"attempting to train trolls for the ballet, the Room of Requirement appears only "
                                   L"when someone is in need of it. To make it appear, one must walk past its hidden "
                                   L"entrance three times while concentrating on what is needed. The room will then "
                                   L"appear, outfitted with whatever is required. To the Hogwarts house-elves, it is "
                                   L"also known as the Come and Go Room.\n"
                                   L"Dumbledore is the first to mention the room, noting that he discovered it at five-thirty "
                                   L"in the morning, filled with chamber pots when he was trying to find a toilet. However, "
                                   L"Dumbledore did not appear to know the Room's secrets. Dobby later told Harry of the "
                                   L"Room in detail and admitted to frequently bringing Winky to the room to cure her bouts "
                                   L"of Butterbeer-induced drunkenness, finding it full of antidotes and a \"nice elf-sized "
                                   L"bed\". Filch was said to find cleaning supplies here when he had run out; when Fred "
                                   L"and George needed a place to hide, it would appear as a broom cupboard. Trelawney "
                                   L"also makes a habit of using it to hide her empty sherry bottles after she is sacked "
                                   L"in Order of the Phoenix. It would seem that when one wishes to hide something it "
                                   L"produces the same room for everyone: the Room of Hidden Things, which is full of many "
                                   L"centuries worth of abandoned objects, such as broken furniture, books, and in one case "
                                   L"a dead quintaped (for more information see Fantastic Beasts and Where to Find Them), "
                                   L"which were presumably forgotten by their owners.\n"
                                   L"Harry learns of the room's abilities from Dobby in Order of the Phoenix, finding it "
                                   L"the perfect location for his Dumbledore's Army meetings, during which it is filled "
                                   L"with bookcases full of Defence Against the Dark Arts volumes, many different kinds "
                                   L"of Dark Detectors, and a plethora of floor cushions for practising defensive spells. "
                                   L"When the D.A. is betrayed, the room is left open, and Pansy Parkinson is able to "
                                   L"retrieve the list of members of the organisation. In Half-Blood Prince Harry uses "
                                   L"the Room of Hidden Things to stash his copy of Advanced Potion-Making, describing "
                                   L"it as the size of a large cathedral and packed to overflowing with items hidden by "
                                   L"Hogwarts inhabitants over the years, such as old potions, clothing, ruined furniture, "
                                   L"an old tiara (which happens to be one of Voldemort's Horcruxes), or books which are "
                                   L"\"no doubt banned or graffitied or stolen\". He later realises that Draco has been "
                                   L"using the room in this state to hide and repair the Vanishing Cabinet to use it to "
                                   L"smuggle Death Eaters into Hogwarts. Ironically, while Harry tries many times to get "
                                   L"into the Room of Requirement to see what Draco is doing, the only time he succeeds "
                                   L"to get into the room (and he is not thinking about Draco), he gains access to the "
                                   L"room where Malfoy has been working.\n"
                                   L"In Deathly Hallows, the students who need a place to hide from the Carrows, two "
                                   L"Death Eater professors, use the room. It is also revealed that the Room of Requirement's "
                                   L"current version can change while still occupied, though should a completely different "
                                   L"version be required (e.g. the Room of Hidden Things instead of DA Headquarters) the "
                                   L"room must be empty. The Room can also answer to the desire of the wizard within the "
                                   L"room, such as providing Harry with a whistle when he needed one during a Dumbledore's "
                                   L"Army meeting, or creating a passage to the Hog's Head (as the room cannot produce food). "
                                   L"Later, Ravenclaw's diadem is found to be one of Voldemort's Horcruxes and has been "
                                   L"hidden in the Room of Hidden Things by Voldemort. Harry, Ron, and Hermione enter the "
                                   L"Room, with Harry knowing that he must look for a place to hide things, and find the "
                                   L"tiara; but they are ambushed by Draco, Crabbe and Goyle. The diadem is finally "
                                   L"destroyed when Crabbe fills this version of the Room with what Hermione believes "
                                   L"to have been Fiendfyre; a destructive magical fire. It is not known if the room "
                                   L"continues to function after the events of Deathly Hallows; Ron expresses concern "
                                   L"that it may have been ruined in all of its forms by the cursed fire.\n"
                                   L"Due to the Room of Requirement not being in a fixed location, it is one of the "
                                   L"select locations in Hogwarts that does not appear on the Marauder's Map.\n"
                                   L"Forbidden Forest\n"
                                   L"The Forbidden Forest is a large, dark enchanted forest in the boundaries of the "
                                   L"school grounds. It is usually referred to simply as \"the Forest\" and in the "
                                   L"film series as the \"Dark Forest\". It is strictly forbidden to all students, except "
                                   L"during Care of Magical Creatures lessons and, on rare occasions, detentions.\n"
                                   L"Among the plant species within the Forest are trees such as beech, oak, pine, "
                                   L"sycamore, yew and knotgrass and thorn undergrowth. Though the Forest is vastly "
                                   L"dense and wild, there are a few paths and clearings. Hagrid, who frequently travels "
                                   L"into the Forest for various reasons, mostly makes these trails. The Forest is also "
                                   L"home to an assortment of creatures, many of them dangerous.\n"
                                   L"In 2017, a Forbidden Forest expansion was added to the Warner Bros. Studio Tour "
                                   L"London - The Making of Harry Potter, enabling fans to explore it for the first time.[24]\n"
                                   L"Hogwarts Express\n"
                                   L"The Hogwarts Express is a train that carries pupils non-stop from Platform 9+3/4 "
                                   L"at King's Cross station in London to Hogsmeade Station, near Hogwarts. Prefects of "
                                   L"the school ride in a separate carriage near the front of the train. The compartments "
                                   L"on the train appear to be lettered; in Half-Blood Prince, the \"Slug Club\" meets in "
                                   L"compartment C.\n"
                                   L"The train began use in the 1850s. Before that, pupils used to reach Hogwarts on brooms "
                                   L"or enchanted carriages.[25]\n"
                                   L"The steam engine used in the film adaptations is the GWR 4900 Class 5972 Olton Hall, "
                                   L"but it was not the first locomotive to be disguised as the Hogwarts Express. To promote "
                                   L"the books, the Southern Railway locomotive 34027 Taw Valley was repainted and renamed "
                                   L"temporarily, but was rejected by director Chris Columbus as looking 'too modern' for "
                                   L"the film. Filming locations for the Hogwarts Express sequences include Goathland on "
                                   L"the North Yorkshire Moors Railway, Kings Cross railway station and the route of the "
                                   L"Jacobite Express which follows the West Highland Line from Fort William to Mallaig in "
                                   L"Scotland, as it crosses the Glenfinnan Viaduct.[26]\n"
                                   L"Several model trains have been made of the Hogwarts Express. An 00 gauge is produced by "
                                   L"Hornby, though this is of a Castle Class locomotive rather than the Hall Class used in "
                                   L"the films. A three-rail H0 gauge model is produced by Marklin, and a two-rail H0/00 was "
                                   L"produced in the early 2000s by Bachmann. Several now-discontinued L gauge models have "
                                   L"been produced by LEGO. Lionel has released an O gauge set in their 2007 catalogue and "
                                   L"a G gauge set for 2008.[27][28]\n"
                                   L"A completely functioning full-scale replica of the Hogwarts Express was created for "
                                   L"The Wizarding World of Harry Potter's expansion at Universal Orlando Resort connecting "
                                   L"King's Cross Station at the Diagon Alley expansion in Universal Studios Florida to the "
                                   L"Hogsmeade station at Islands of Adventure,[29] manufactured by Doppelmayr Garaventa Group "
                                   L"in the form of a funicular railway people mover.[30] The Hogwarts Express King's Cross "
                                   L"Station features a wall between Platforms 9 and 10, where guests can \"walk through\" "
                                   L"to get to Platform 9+3/4, as in the first film.\n";





            using namespace marty_draw_context;

            //std::wstring textForTestCompress = loremIpsumLong;
            //std::wstring textForTestCompress = loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki;
            //std::wstring textForTestCompress = loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki + hogwartsWiki1;
            //std::wstring textForTestCompress = loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki + hogwartsWiki1 + hogwartsWiki2;
            //std::wstring textForTestCompress = loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki + hogwartsWiki1 + hogwartsWiki2 + hogwartsWiki3;
            std::wstring textForTestCompress = loremIpsumArticleWiki + hogwartsWiki1 + hogwartsWiki2 + hogwartsWiki3;

            auto textForTestCompressSize = textForTestCompress.size();

            std::size_t nWords  = 0;
            std::size_t nChars  = 0;
            std::size_t nPackedChars = 0;
            std::map<char, std::size_t> charCounts;
            
            std::vector<std::wstring> words;
            marty::Decimal avgWordLen   = 0;
            std::wstring compressedText = simple_text_compress(textForTestCompress, words, charCounts, nWords, nChars, nPackedChars);
            std::size_t  dictBytes      = calcWordsBytes(words, avgWordLen);
            std::size_t  textBytes      = 2*compressedText.size();   // один символ или слово - всегда два байта
            textBytes -= nPackedChars; // на упакованные символы нужно на байт меньше
            std::size_t  textBytes12    = 3*compressedText.size()/2; // если на символ или слово использовать 12 бит
            textBytes12 -= nPackedChars; // на упакованные символы нужно на байт меньше
            std::size_t  totalBytes     = textBytes   + dictBytes;
            std::size_t  totalBytes12   = textBytes12 + dictBytes;
            int          overhead       = (int)(100*totalBytes/textForTestCompressSize-100);
            int          overhead12     = (int)(100*totalBytes12/textForTestCompressSize-100);

            MARTY_IDC_ARG_USED(avgWordLen);
            MARTY_IDC_ARG_USED(compressedText);
            MARTY_IDC_ARG_USED(dictBytes     );
            MARTY_IDC_ARG_USED(textBytes     );
            MARTY_IDC_ARG_USED(textBytes12);
            MARTY_IDC_ARG_USED(totalBytes  );
            MARTY_IDC_ARG_USED(totalBytes12);
            MARTY_IDC_ARG_USED(overhead    );
            MARTY_IDC_ARG_USED(overhead12  );
            //MARTY_IDC_ARG_USED();

            /*
            lout << "Lorem ipsum size : " << textForTestCompress.size() << "\n";
            lout << "Words in dict    : " << words.size() << "\n";
            lout << "Total words      : " << nWords << "\n";
            lout << "Avg word len     : " << avgWordLen.toString(2) << "\n";
            lout << "Total single chs : " << nChars << "\n";
            lout << "Total packed chs : " << nPackedChars << "\n";
            lout << "Dictionary   size: " << dictBytes << "\n";
            lout << "Text         size: " << textBytes << "\n";
            lout << "Text (12bit) size: " << textBytes12 << "\n";
            lout << "Total (text+dict): " << totalBytes << "\n";
            lout << "Total (12bit)    : " << totalBytes12 << "\n";
            lout << "Overhead         : " << overhead << "%\n";
            lout << "Overhead (12bit) : " << overhead12 << "%\n";
            lout << "Char counters (total: " << charCounts.size() <<"):\n";

            std::map<char, std::size_t>::const_iterator ccIt = charCounts.begin();
            for(; ccIt!=charCounts.end(); ++ccIt)
            {
                char ch         = ccIt->first;
                std::size_t cnt = ccIt->second;
                unsigned uch = (unsigned)(unsigned char)ch;
                if (uch<=(unsigned)' ')
                {
                    lout << "  ' ' (" << uch << ") - " << cnt << "\n";
                }
                else
                {
                    lout << "  '" << ch << "' (" << uch << ") - " << cnt << "\n";
                }

            }
            */

            // // loremIpsumLong
            // Lorem ipsum  size: 1731
            // Words in dict    : 186
            // Total words      : 249
            // Total single chs : 295
            // Dictionary   size: 1366
            // Text         size: 1088
            // Text (12bit) size: 816
            // Total (text+dict): 2454
            // Total (12bit)    : 2182
            // Overhead         : 41%
            // Overhead (12bit) : 26%

            // // loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki

            // // loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki + hogwartsWiki;

            // // std::wstring textForTestCompress = loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki + hogwartsWiki2;

            // // std::wstring textForTestCompress = loremIpsumLong + loremIpsumTiny + loremIpsumShort + loremIpsumArticleWiki + hogwartsWiki2 + hogwartsWiki3;

            // // std::wstring textForTestCompress = loremIpsumArticleWiki + hogwartsWiki2 + hogwartsWiki3;
